FORMAT: 1A
HOST: http://localhost:8080

# leadTracker

Lead Manager API

## Person information [/persons/:idperson]

Obtain data for person with id : 1

### Public data [GET]

+ Response 200 (application/json)

        {
            "person": {
            id:1
            firstname : "Fabrice"
            lastname : "Sznajderman"
            gender : "male"
            position : "developer"
            status : "contractor"
            technologies : ["scala", "lagom"]
            experience : 16
            isTraining : false
            showSensitive : true
            links:[
                    {
                        "rel": "contacts",
                        "href": "http://localhost:8080/persons/1/contacts"
                    }, 
                    {
                        "rel": "self",
                        "href": "http://localhost:8080/persons/1"
                    }
                ]
           }
        }
       
+ Response 404 (application/json)
        
        {
            "error":{
                "code" : "person_not_found"
                "message : "Person with id 1 not found"
        }


### Update data [PUT]

    +Body
    {
    person : {
        id:1
        firstname : "Michel"
    }
    
+ Response 201 (application/json)

    

## Person sensitive information [/persons/:idperson/sensitive]

### Sensitive data for one person [GET]
           
+ Response 200 (application/json)

        {
            "person": {
            id:1
            firstname : "Fabrice"
            lastname : "Sznajderman"
            gender : "male"
            position : "developer"
            status : "contractor"
            technologies : ["scala", "lagom"]
            experience : 16
            isTraining : false
            showSensitive : true
            links:[
                    {
                        "rel": "contacts",
                        "href": "http://localhost:8080/persons/1/contacts"
                    }, 
                    {
                        "rel": "self",
                        "href": "http://localhost:8080/persons/1"
                    }
                ]
           }
        }