FORMAT: 1A
HOST: http://localhost:8080

# leadTracker

Lead Manager API

## Person information [/persons/:idperson]

Obtain data for person with id : 1

### Read person [GET]

+ Response 200 (application/json)

        {
            "person": {
            id:1
            firstname : "Fabrice"
            lastname : "Sznajderman"
            gender : "male"
            position : "developer"
            status : "contractor"
            technologies : ["scala", "lagom"]
            experience : 16
            isTraining : false
            showSensitive : true
            links:[
                    {
                        "rel": "contacts",
                        "href": "http://localhost:8080/persons/1/contacts"
                    }, 
                    {
                        "rel": "self",
                        "href": "http://localhost:8080/persons/1"
                    },
                    {
                        "rel": "sensitive",
                        "href": "http://localhost:8080/persons/1/sensitive"
                    }
                ]
           }
        }
       
+ Response 404 (application/json)
        
        {
            "error":{
                "code" : "person_not_found"
                "message : "Person with id 1 not found"
        }


### Update person [PUT]

+ Request (application/json)
    
        {
            "person" : {
                id:1
                firstname : "Michel"
            }
        }
    
+ Response 201 (application/json)
        
        {
            message : "person with id 1 updated"
        }

    

## Person sensitive information [/persons/:idperson/sensitive]

### Read Sensitive data for a person [GET]
           
+ Response 200 (application/json)

        {
            "person": {
            id:1
            email
            phone number
            company
            workLocation : "Paris"
            lookingForAJob : "false"
            links:[
                    {
                        "rel": "self",
                        "href": "http://localhost:8080/persons/1/sensitive"
                    },
                    {
                        "rel": "person",
                        "href": "http://localhost:8080/persons/1"
                    },
                    {
                        "rel": "contacts",
                        "href": "http://localhost:8080/persons/1/contacts"
                    },
                    
                ]
           }
        }