FORMAT: 1A
HOST: http://localhost:8080

# leadTracker

Lead Manager API

## Person information [/persons/:idperson]

Obtain data for person with id : 1

### Read person [GET]

+ Response 200 (application/json)

        {
            "person": {
            id:1
            firstname : "Fabrice"
            lastname : "Sznajderman"
            gender : "male"
            position : "developer"
            status : "contractor"
            technologies : ["scala", "lagom"]
            experience : 16
            isTraining : false
            showSensitive : true
            profil : "attendee"
            links:[
                    {
                        "rel": "contacts",
                        "href": "http://localhost:8080/persons/1/contacts"
                    }, 
                    {
                        "rel": "self",
                        "href": "http://localhost:8080/persons/1"
                    },
                    {
                        "rel": "sensitive",
                        "href": "http://localhost:8080/persons/1/sensitive"
                    }
                ]
           }
        }
       
+ Response 404 (application/json)
        
        {
            "error":{
                "code" : "person_not_found"
                "message : "Person with id 1 not found"
                }
        }


### Update person [PUT]

+ Request (application/json)
    
        {
            firstname : "Michel"
            position : "developer"
        }
    
+ Response 201 (application/json)
        
        {
            "info":{
            message : "person with id 1 updated"
            }
        }

    

## Person sensitive information [/persons/:idperson/sensitive]

Obtain SENSITIVE data for person with id : 1

### Read sensitive data for a person [GET]
           
+ Response 200 (application/json)

        {
            "person": {
            id:1
            email
            phone number
            company
            workLocation : "Paris"
            lookingForAJob : "false"
            links:[
                    {
                        "rel": "self",
                        "href": "http://localhost:8080/persons/1/sensitive"
                    },
                    {
                        "rel": "person",
                        "href": "http://localhost:8080/persons/1"
                    },
                    {
                        "rel": "contacts",
                        "href": "http://localhost:8080/persons/1/contacts"
                    },
                    
                ]
           }
        }
        
## Notification information [/notifications/:idperson]

Obtain notification for person with id : 1

### Read all notifications for person [GET]

+ Response 200 (application/json)
        
        {
         "notifications" : [
            {
                "id" : 2
                "type" : "update"
                "message": "[person2 has updated his profil"
            },
            {
                "id" : 10
                "type" : "askForUpdate"
                "message": "[person33] ask you to update your profile"
            }
         
         ]
         links : [
            {
                "rel": "self",
                "href": "http://localhost:8080/notifications/1"
            },
            {
                "rel": "person",
                "href": "http://localhost:8080/persons/1"
            }
         ]
         
        }
        
+ Response 404 (application/json)

        {
            "error":{
                "code" : "notifications_not_found"
                "message" : "Notification for person with id 1 are not found"
        }

## Notification information by type [/notifications/:idperson/type/:type]

Obtain notification for person with id : 1 by type of notification

### Read all notifications for person by type [GET]

+ Response 200 (application/json)
        
        {
         "notifications" : [
            {
                "id" : 2
                "type" : "askForUpdate"
                "message": "[person35] ask you to update your profile"
            },
            {
                "id" : 10
                "type" : "askForUpdate"
                "message": "[person33] ask you to update your profile"
            }
         
         ]
         links : [
            {
                "rel": "self",
                "href": "http://localhost:8080/notifications/1/type/askForUpdate"
            },
            {
                "rel": "person",
                "href": "http://localhost:8080/persons/1"
            }
         ]
         
        }
        
+ Response 404 (application/json)

        {
            "error":{
                "code" : "notifications_not_found"
                "message : "Notification for person with id 1 are not found"
                }
        }
        
## contacts [/persons/:idperson/contacts]

Obtain contact for person with id : 1

### Read person contacts [GET]

+ Response 200 (application/json)

        {
            "contacts":[
                {
                    "firstname":"Michel"
                    "lastname" : "Paul"
                    links:[
                        {
                            "rel": "sensitive",
                            "href": "http://localhost:8080/persons/10/sensitive"
                        },
                        {
                            "rel": "self",
                            "href": "http://localhost:8080/persons/10"
                        },
                        {
                            "rel": "contacts",
                            "href": "http://localhost:8080/persons/10/contacts"
                        }
                    ]
                    
                },
                 {
                    "firstname":"Louisa"
                    "lastname" : "Delfont"
                    links:[
                        {
                            "rel": "sensitive",
                            "href": "http://localhost:8080/persons/14/sensitive"
                        },
                        {
                            "rel": "self",
                            "href": "http://localhost:8080/persons/14"
                        },
                        {
                            "rel": "contacts",
                            "href": "http://localhost:8080/persons/14/contacts"
                        }
                    ]
                    
                }
                
              
            ]
        }